//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paonia_Backend.Databse
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaf
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string SenderEmailID { get; set; }
        public string Password { get; set; }
        public string PhoneNumber { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverEmailId { get; set; }
        public Nullable<System.DateTime> LeaveStart { get; set; }
        public Nullable<System.DateTime> LeaveEnd { get; set; }
        public string LeaveType { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual User User { get; set; }
    }
}
