//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paonia_Backend.Databse
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeType
    {
        public int Id { get; set; }
        public string EmpTypeCode { get; set; }
        public string EmpTypeName { get; set; }
        public string EmpTypeStatus { get; set; }
    }
}
